// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL4LJtsDMKLkyMvCrLtkXFvimsbzs0qTM',
    appId: '1:467388574018:web:1912b9cbc84898179440db',
    messagingSenderId: '467388574018',
    projectId: 'poultryfarmapp-31135',
    authDomain: 'poultryfarmapp-31135.firebaseapp.com',
    storageBucket: 'poultryfarmapp-31135.firebasestorage.app',
    measurementId: 'G-W2NJESERDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1_Mda1QCIx6S010-YzBZKMtptma3flB4',
    appId: '1:467388574018:android:c4ef48af71c673819440db',
    messagingSenderId: '467388574018',
    projectId: 'poultryfarmapp-31135',
    storageBucket: 'poultryfarmapp-31135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1cvvk-HtYSJpn-jGmd7SPtBaI2piKQGc',
    appId: '1:467388574018:ios:34fe9c33a4414a2b9440db',
    messagingSenderId: '467388574018',
    projectId: 'poultryfarmapp-31135',
    storageBucket: 'poultryfarmapp-31135.firebasestorage.app',
    iosBundleId: 'com.example.chickenTrackingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1cvvk-HtYSJpn-jGmd7SPtBaI2piKQGc',
    appId: '1:467388574018:ios:34fe9c33a4414a2b9440db',
    messagingSenderId: '467388574018',
    projectId: 'poultryfarmapp-31135',
    storageBucket: 'poultryfarmapp-31135.firebasestorage.app',
    iosBundleId: 'com.example.chickenTrackingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL4LJtsDMKLkyMvCrLtkXFvimsbzs0qTM',
    appId: '1:467388574018:web:b0882f3f38b409569440db',
    messagingSenderId: '467388574018',
    projectId: 'poultryfarmapp-31135',
    authDomain: 'poultryfarmapp-31135.firebaseapp.com',
    storageBucket: 'poultryfarmapp-31135.firebasestorage.app',
    measurementId: 'G-8FPZBWHN6P',
  );
}
